[package]
name = "cyo-mimalloc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
documentation = "https://docs.rs/cyo-mimalloc"
description = "mimalloc V3 as a Rust global allocator"
readme = "../README.md"
keywords.workspace = true
categories = ["memory-management", "no-std::no-alloc"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]

[dependencies]
cyo-mimalloc-sys = { workspace = true }
