[workspace]
members = ["cyo-mimalloc-sys", "cyo-mimalloc"]
resolver = "3"

[workspace.package]
version = "0.5.4"
edition = "2024"
rust-version = "1.96.0"
license = "Apache-2.0"
repository = "https://github.com/cyo-alloc/mimalloc"
authors = ["Tip ten Brink <tip@tenbrinkmeijs.com>"]
description = "High-performance mimalloc V3 bindings for Rust"
keywords = ["allocator", "mimalloc", "memory"]

[workspace.dependencies]
cyo-mimalloc = { path = "cyo-mimalloc", version = "0.5.4" }
cyo-mimalloc-sys = { path = "cyo-mimalloc-sys", version = "0.5.4" }
cc = "1.4.6"
